# This is a basic workflow to help you get started with Actions

name: Android CI

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:    
 build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: send custom message with args
      uses: actions/checkout@master
      
    - name: Send telegram message  
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: The ${{ github.event_name }} event triggered first step.

    - name: set up JDK 1.8
      uses: actions/checkout@v2
      with:
        java-version: 1.8
        name: Build Debug APK
        run: bash ./gradlew :app:assembleDebug

#Step to Submit the generated APK to Firebase App Distribution
 uploadapk:
     name: Publish build
     runs-on: ubuntu-latest
     needs: build
     steps: 
       - name: Upload artifact to Firebase App Distribution
         uses: wzieba/Firebase-Distribution-Github-Action@v1
         with:
           appId: ${{ secrets.FIREBASE_APP_ID }}
           token: ${{ secrets.FIREBASE_TOKEN }}
           file: app/build/outputs/apk/debug/app-debug.apk
                          
       - name: Send job status to telegram
         uses: robotomize/notify-telegram@v0.1.0
         with:
           chat: ${{ secrets.TELEGRAM_CHAT }} # user id or channel name secret
           token: ${{ secrets.TELEGRAM_TOKEN }} # token secret
           status: ${{ job.status }} # do not modify this line

       - name: Upload APK
         uses: actions/upload-artifact@v2
         with:
           name: App
           path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
        
       - name: Upload to dropbox 
         uses: deka0106/upload-to-dropbox@v1
         with:
           dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
           file: app/build/outputs/apk/debug/app-debug.apk
           path: /appbuilds/app-debug.apk
